# Configuration for promtail chart, see https://github.com/grafana/helm-charts/tree/main/charts/promtail

config:
  # publish data to loki
  lokiAddress: http://loki:3100/loki/api/v1/push

  snippets:
    pipelineStages:
    - cri: { }
    - json:
        expressions:
          cluster: cluster
          machine: machine
    - labels:
        cluster:
        machine:
