//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/core/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfterClusterUpgradeRequest) DeepCopyInto(out *AfterClusterUpgradeRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfterClusterUpgradeRequest.
func (in *AfterClusterUpgradeRequest) DeepCopy() *AfterClusterUpgradeRequest {
	if in == nil {
		return nil
	}
	out := new(AfterClusterUpgradeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfterClusterUpgradeRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfterClusterUpgradeResponse) DeepCopyInto(out *AfterClusterUpgradeResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonRetryResponse = in.CommonRetryResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfterClusterUpgradeResponse.
func (in *AfterClusterUpgradeResponse) DeepCopy() *AfterClusterUpgradeResponse {
	if in == nil {
		return nil
	}
	out := new(AfterClusterUpgradeResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfterClusterUpgradeResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfterControlPlaneInitializedRequest) DeepCopyInto(out *AfterControlPlaneInitializedRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfterControlPlaneInitializedRequest.
func (in *AfterControlPlaneInitializedRequest) DeepCopy() *AfterControlPlaneInitializedRequest {
	if in == nil {
		return nil
	}
	out := new(AfterControlPlaneInitializedRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfterControlPlaneInitializedRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfterControlPlaneInitializedResponse) DeepCopyInto(out *AfterControlPlaneInitializedResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonResponse = in.CommonResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfterControlPlaneInitializedResponse.
func (in *AfterControlPlaneInitializedResponse) DeepCopy() *AfterControlPlaneInitializedResponse {
	if in == nil {
		return nil
	}
	out := new(AfterControlPlaneInitializedResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfterControlPlaneInitializedResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfterControlPlaneUpgradeRequest) DeepCopyInto(out *AfterControlPlaneUpgradeRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	in.Cluster.DeepCopyInto(&out.Cluster)
	if in.ControlPlaneUpgrades != nil {
		in, out := &in.ControlPlaneUpgrades, &out.ControlPlaneUpgrades
		*out = make([]UpgradeStepInfo, len(*in))
		copy(*out, *in)
	}
	if in.WorkersUpgrades != nil {
		in, out := &in.WorkersUpgrades, &out.WorkersUpgrades
		*out = make([]UpgradeStepInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfterControlPlaneUpgradeRequest.
func (in *AfterControlPlaneUpgradeRequest) DeepCopy() *AfterControlPlaneUpgradeRequest {
	if in == nil {
		return nil
	}
	out := new(AfterControlPlaneUpgradeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfterControlPlaneUpgradeRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfterControlPlaneUpgradeResponse) DeepCopyInto(out *AfterControlPlaneUpgradeResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonRetryResponse = in.CommonRetryResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfterControlPlaneUpgradeResponse.
func (in *AfterControlPlaneUpgradeResponse) DeepCopy() *AfterControlPlaneUpgradeResponse {
	if in == nil {
		return nil
	}
	out := new(AfterControlPlaneUpgradeResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfterControlPlaneUpgradeResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfterWorkersUpgradeRequest) DeepCopyInto(out *AfterWorkersUpgradeRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	in.Cluster.DeepCopyInto(&out.Cluster)
	if in.ControlPlaneUpgrades != nil {
		in, out := &in.ControlPlaneUpgrades, &out.ControlPlaneUpgrades
		*out = make([]UpgradeStepInfo, len(*in))
		copy(*out, *in)
	}
	if in.WorkersUpgrades != nil {
		in, out := &in.WorkersUpgrades, &out.WorkersUpgrades
		*out = make([]UpgradeStepInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfterWorkersUpgradeRequest.
func (in *AfterWorkersUpgradeRequest) DeepCopy() *AfterWorkersUpgradeRequest {
	if in == nil {
		return nil
	}
	out := new(AfterWorkersUpgradeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfterWorkersUpgradeRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfterWorkersUpgradeResponse) DeepCopyInto(out *AfterWorkersUpgradeResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonRetryResponse = in.CommonRetryResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfterWorkersUpgradeResponse.
func (in *AfterWorkersUpgradeResponse) DeepCopy() *AfterWorkersUpgradeResponse {
	if in == nil {
		return nil
	}
	out := new(AfterWorkersUpgradeResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfterWorkersUpgradeResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeClusterCreateRequest) DeepCopyInto(out *BeforeClusterCreateRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeClusterCreateRequest.
func (in *BeforeClusterCreateRequest) DeepCopy() *BeforeClusterCreateRequest {
	if in == nil {
		return nil
	}
	out := new(BeforeClusterCreateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeforeClusterCreateRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeClusterCreateResponse) DeepCopyInto(out *BeforeClusterCreateResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonRetryResponse = in.CommonRetryResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeClusterCreateResponse.
func (in *BeforeClusterCreateResponse) DeepCopy() *BeforeClusterCreateResponse {
	if in == nil {
		return nil
	}
	out := new(BeforeClusterCreateResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeforeClusterCreateResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeClusterDeleteRequest) DeepCopyInto(out *BeforeClusterDeleteRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeClusterDeleteRequest.
func (in *BeforeClusterDeleteRequest) DeepCopy() *BeforeClusterDeleteRequest {
	if in == nil {
		return nil
	}
	out := new(BeforeClusterDeleteRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeforeClusterDeleteRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeClusterDeleteResponse) DeepCopyInto(out *BeforeClusterDeleteResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonRetryResponse = in.CommonRetryResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeClusterDeleteResponse.
func (in *BeforeClusterDeleteResponse) DeepCopy() *BeforeClusterDeleteResponse {
	if in == nil {
		return nil
	}
	out := new(BeforeClusterDeleteResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeforeClusterDeleteResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeClusterUpgradeRequest) DeepCopyInto(out *BeforeClusterUpgradeRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	in.Cluster.DeepCopyInto(&out.Cluster)
	if in.ControlPlaneUpgrades != nil {
		in, out := &in.ControlPlaneUpgrades, &out.ControlPlaneUpgrades
		*out = make([]UpgradeStepInfo, len(*in))
		copy(*out, *in)
	}
	if in.WorkersUpgrades != nil {
		in, out := &in.WorkersUpgrades, &out.WorkersUpgrades
		*out = make([]UpgradeStepInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeClusterUpgradeRequest.
func (in *BeforeClusterUpgradeRequest) DeepCopy() *BeforeClusterUpgradeRequest {
	if in == nil {
		return nil
	}
	out := new(BeforeClusterUpgradeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeforeClusterUpgradeRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeClusterUpgradeResponse) DeepCopyInto(out *BeforeClusterUpgradeResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonRetryResponse = in.CommonRetryResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeClusterUpgradeResponse.
func (in *BeforeClusterUpgradeResponse) DeepCopy() *BeforeClusterUpgradeResponse {
	if in == nil {
		return nil
	}
	out := new(BeforeClusterUpgradeResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeforeClusterUpgradeResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeControlPlaneUpgradeRequest) DeepCopyInto(out *BeforeControlPlaneUpgradeRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	in.Cluster.DeepCopyInto(&out.Cluster)
	if in.ControlPlaneUpgrades != nil {
		in, out := &in.ControlPlaneUpgrades, &out.ControlPlaneUpgrades
		*out = make([]UpgradeStepInfo, len(*in))
		copy(*out, *in)
	}
	if in.WorkersUpgrades != nil {
		in, out := &in.WorkersUpgrades, &out.WorkersUpgrades
		*out = make([]UpgradeStepInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeControlPlaneUpgradeRequest.
func (in *BeforeControlPlaneUpgradeRequest) DeepCopy() *BeforeControlPlaneUpgradeRequest {
	if in == nil {
		return nil
	}
	out := new(BeforeControlPlaneUpgradeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeforeControlPlaneUpgradeRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeControlPlaneUpgradeResponse) DeepCopyInto(out *BeforeControlPlaneUpgradeResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonRetryResponse = in.CommonRetryResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeControlPlaneUpgradeResponse.
func (in *BeforeControlPlaneUpgradeResponse) DeepCopy() *BeforeControlPlaneUpgradeResponse {
	if in == nil {
		return nil
	}
	out := new(BeforeControlPlaneUpgradeResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeforeControlPlaneUpgradeResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeWorkersUpgradeRequest) DeepCopyInto(out *BeforeWorkersUpgradeRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	in.Cluster.DeepCopyInto(&out.Cluster)
	if in.ControlPlaneUpgrades != nil {
		in, out := &in.ControlPlaneUpgrades, &out.ControlPlaneUpgrades
		*out = make([]UpgradeStepInfo, len(*in))
		copy(*out, *in)
	}
	if in.WorkersUpgrades != nil {
		in, out := &in.WorkersUpgrades, &out.WorkersUpgrades
		*out = make([]UpgradeStepInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeWorkersUpgradeRequest.
func (in *BeforeWorkersUpgradeRequest) DeepCopy() *BeforeWorkersUpgradeRequest {
	if in == nil {
		return nil
	}
	out := new(BeforeWorkersUpgradeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeforeWorkersUpgradeRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeWorkersUpgradeResponse) DeepCopyInto(out *BeforeWorkersUpgradeResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonRetryResponse = in.CommonRetryResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeWorkersUpgradeResponse.
func (in *BeforeWorkersUpgradeResponse) DeepCopy() *BeforeWorkersUpgradeResponse {
	if in == nil {
		return nil
	}
	out := new(BeforeWorkersUpgradeResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeforeWorkersUpgradeResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Builtins) DeepCopyInto(out *Builtins) {
	*out = *in
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(ClusterBuiltins)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(ControlPlaneBuiltins)
		(*in).DeepCopyInto(*out)
	}
	if in.MachineDeployment != nil {
		in, out := &in.MachineDeployment, &out.MachineDeployment
		*out = new(MachineDeploymentBuiltins)
		(*in).DeepCopyInto(*out)
	}
	if in.MachinePool != nil {
		in, out := &in.MachinePool, &out.MachinePool
		*out = new(MachinePoolBuiltins)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Builtins.
func (in *Builtins) DeepCopy() *Builtins {
	if in == nil {
		return nil
	}
	out := new(Builtins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanUpdateMachineRequest) DeepCopyInto(out *CanUpdateMachineRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	in.Current.DeepCopyInto(&out.Current)
	in.Desired.DeepCopyInto(&out.Desired)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanUpdateMachineRequest.
func (in *CanUpdateMachineRequest) DeepCopy() *CanUpdateMachineRequest {
	if in == nil {
		return nil
	}
	out := new(CanUpdateMachineRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CanUpdateMachineRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanUpdateMachineRequestObjects) DeepCopyInto(out *CanUpdateMachineRequestObjects) {
	*out = *in
	in.Machine.DeepCopyInto(&out.Machine)
	in.InfrastructureMachine.DeepCopyInto(&out.InfrastructureMachine)
	in.BootstrapConfig.DeepCopyInto(&out.BootstrapConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanUpdateMachineRequestObjects.
func (in *CanUpdateMachineRequestObjects) DeepCopy() *CanUpdateMachineRequestObjects {
	if in == nil {
		return nil
	}
	out := new(CanUpdateMachineRequestObjects)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanUpdateMachineResponse) DeepCopyInto(out *CanUpdateMachineResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonResponse = in.CommonResponse
	in.MachinePatch.DeepCopyInto(&out.MachinePatch)
	in.InfrastructureMachinePatch.DeepCopyInto(&out.InfrastructureMachinePatch)
	in.BootstrapConfigPatch.DeepCopyInto(&out.BootstrapConfigPatch)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanUpdateMachineResponse.
func (in *CanUpdateMachineResponse) DeepCopy() *CanUpdateMachineResponse {
	if in == nil {
		return nil
	}
	out := new(CanUpdateMachineResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CanUpdateMachineResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanUpdateMachineSetRequest) DeepCopyInto(out *CanUpdateMachineSetRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	in.Current.DeepCopyInto(&out.Current)
	in.Desired.DeepCopyInto(&out.Desired)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanUpdateMachineSetRequest.
func (in *CanUpdateMachineSetRequest) DeepCopy() *CanUpdateMachineSetRequest {
	if in == nil {
		return nil
	}
	out := new(CanUpdateMachineSetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CanUpdateMachineSetRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanUpdateMachineSetRequestObjects) DeepCopyInto(out *CanUpdateMachineSetRequestObjects) {
	*out = *in
	in.MachineSet.DeepCopyInto(&out.MachineSet)
	in.InfrastructureMachineTemplate.DeepCopyInto(&out.InfrastructureMachineTemplate)
	in.BootstrapConfigTemplate.DeepCopyInto(&out.BootstrapConfigTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanUpdateMachineSetRequestObjects.
func (in *CanUpdateMachineSetRequestObjects) DeepCopy() *CanUpdateMachineSetRequestObjects {
	if in == nil {
		return nil
	}
	out := new(CanUpdateMachineSetRequestObjects)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanUpdateMachineSetResponse) DeepCopyInto(out *CanUpdateMachineSetResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonResponse = in.CommonResponse
	in.MachineSetPatch.DeepCopyInto(&out.MachineSetPatch)
	in.InfrastructureMachineTemplatePatch.DeepCopyInto(&out.InfrastructureMachineTemplatePatch)
	in.BootstrapConfigTemplatePatch.DeepCopyInto(&out.BootstrapConfigTemplatePatch)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanUpdateMachineSetResponse.
func (in *CanUpdateMachineSetResponse) DeepCopy() *CanUpdateMachineSetResponse {
	if in == nil {
		return nil
	}
	out := new(CanUpdateMachineSetResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CanUpdateMachineSetResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBuiltins) DeepCopyInto(out *ClusterBuiltins) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(v1beta1.ObjectMeta)
		(*in).DeepCopyInto(*out)
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(ClusterTopologyBuiltins)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(ClusterNetworkBuiltins)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBuiltins.
func (in *ClusterBuiltins) DeepCopy() *ClusterBuiltins {
	if in == nil {
		return nil
	}
	out := new(ClusterBuiltins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkBuiltins) DeepCopyInto(out *ClusterNetworkBuiltins) {
	*out = *in
	if in.ServiceDomain != nil {
		in, out := &in.ServiceDomain, &out.ServiceDomain
		*out = new(string)
		**out = **in
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkBuiltins.
func (in *ClusterNetworkBuiltins) DeepCopy() *ClusterNetworkBuiltins {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkBuiltins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTopologyBuiltins) DeepCopyInto(out *ClusterTopologyBuiltins) {
	*out = *in
	out.ClassRef = in.ClassRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTopologyBuiltins.
func (in *ClusterTopologyBuiltins) DeepCopy() *ClusterTopologyBuiltins {
	if in == nil {
		return nil
	}
	out := new(ClusterTopologyBuiltins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTopologyClusterClassRefBuiltins) DeepCopyInto(out *ClusterTopologyClusterClassRefBuiltins) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTopologyClusterClassRefBuiltins.
func (in *ClusterTopologyClusterClassRefBuiltins) DeepCopy() *ClusterTopologyClusterClassRefBuiltins {
	if in == nil {
		return nil
	}
	out := new(ClusterTopologyClusterClassRefBuiltins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonRequest) DeepCopyInto(out *CommonRequest) {
	*out = *in
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonRequest.
func (in *CommonRequest) DeepCopy() *CommonRequest {
	if in == nil {
		return nil
	}
	out := new(CommonRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonResponse) DeepCopyInto(out *CommonResponse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonResponse.
func (in *CommonResponse) DeepCopy() *CommonResponse {
	if in == nil {
		return nil
	}
	out := new(CommonResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonRetryResponse) DeepCopyInto(out *CommonRetryResponse) {
	*out = *in
	out.CommonResponse = in.CommonResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonRetryResponse.
func (in *CommonRetryResponse) DeepCopy() *CommonRetryResponse {
	if in == nil {
		return nil
	}
	out := new(CommonRetryResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneBuiltins) DeepCopyInto(out *ControlPlaneBuiltins) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(v1beta1.ObjectMeta)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.MachineTemplate != nil {
		in, out := &in.MachineTemplate, &out.MachineTemplate
		*out = new(ControlPlaneMachineTemplateBuiltins)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneBuiltins.
func (in *ControlPlaneBuiltins) DeepCopy() *ControlPlaneBuiltins {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneBuiltins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneMachineTemplateBuiltins) DeepCopyInto(out *ControlPlaneMachineTemplateBuiltins) {
	*out = *in
	out.InfrastructureRef = in.InfrastructureRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneMachineTemplateBuiltins.
func (in *ControlPlaneMachineTemplateBuiltins) DeepCopy() *ControlPlaneMachineTemplateBuiltins {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneMachineTemplateBuiltins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneMachineTemplateInfrastructureRefBuiltins) DeepCopyInto(out *ControlPlaneMachineTemplateInfrastructureRefBuiltins) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneMachineTemplateInfrastructureRefBuiltins.
func (in *ControlPlaneMachineTemplateInfrastructureRefBuiltins) DeepCopy() *ControlPlaneMachineTemplateInfrastructureRefBuiltins {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneMachineTemplateInfrastructureRefBuiltins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoverVariablesRequest) DeepCopyInto(out *DiscoverVariablesRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoverVariablesRequest.
func (in *DiscoverVariablesRequest) DeepCopy() *DiscoverVariablesRequest {
	if in == nil {
		return nil
	}
	out := new(DiscoverVariablesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoverVariablesRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoverVariablesResponse) DeepCopyInto(out *DiscoverVariablesResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonResponse = in.CommonResponse
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]v1beta1.ClusterClassVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoverVariablesResponse.
func (in *DiscoverVariablesResponse) DeepCopy() *DiscoverVariablesResponse {
	if in == nil {
		return nil
	}
	out := new(DiscoverVariablesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoverVariablesResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryRequest) DeepCopyInto(out *DiscoveryRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryRequest.
func (in *DiscoveryRequest) DeepCopy() *DiscoveryRequest {
	if in == nil {
		return nil
	}
	out := new(DiscoveryRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveryRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryResponse) DeepCopyInto(out *DiscoveryResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonResponse = in.CommonResponse
	if in.Handlers != nil {
		in, out := &in.Handlers, &out.Handlers
		*out = make([]ExtensionHandler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryResponse.
func (in *DiscoveryResponse) DeepCopy() *DiscoveryResponse {
	if in == nil {
		return nil
	}
	out := new(DiscoveryResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveryResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionHandler) DeepCopyInto(out *ExtensionHandler) {
	*out = *in
	out.RequestHook = in.RequestHook
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.FailurePolicy != nil {
		in, out := &in.FailurePolicy, &out.FailurePolicy
		*out = new(FailurePolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionHandler.
func (in *ExtensionHandler) DeepCopy() *ExtensionHandler {
	if in == nil {
		return nil
	}
	out := new(ExtensionHandler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratePatchesRequest) DeepCopyInto(out *GeneratePatchesRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]Variable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GeneratePatchesRequestItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratePatchesRequest.
func (in *GeneratePatchesRequest) DeepCopy() *GeneratePatchesRequest {
	if in == nil {
		return nil
	}
	out := new(GeneratePatchesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GeneratePatchesRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratePatchesRequestItem) DeepCopyInto(out *GeneratePatchesRequestItem) {
	*out = *in
	out.HolderReference = in.HolderReference
	in.Object.DeepCopyInto(&out.Object)
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]Variable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratePatchesRequestItem.
func (in *GeneratePatchesRequestItem) DeepCopy() *GeneratePatchesRequestItem {
	if in == nil {
		return nil
	}
	out := new(GeneratePatchesRequestItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratePatchesResponse) DeepCopyInto(out *GeneratePatchesResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonResponse = in.CommonResponse
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GeneratePatchesResponseItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratePatchesResponse.
func (in *GeneratePatchesResponse) DeepCopy() *GeneratePatchesResponse {
	if in == nil {
		return nil
	}
	out := new(GeneratePatchesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GeneratePatchesResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratePatchesResponseItem) DeepCopyInto(out *GeneratePatchesResponseItem) {
	*out = *in
	if in.Patch != nil {
		in, out := &in.Patch, &out.Patch
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratePatchesResponseItem.
func (in *GeneratePatchesResponseItem) DeepCopy() *GeneratePatchesResponseItem {
	if in == nil {
		return nil
	}
	out := new(GeneratePatchesResponseItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenerateUpgradePlanRequest) DeepCopyInto(out *GenerateUpgradePlanRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenerateUpgradePlanRequest.
func (in *GenerateUpgradePlanRequest) DeepCopy() *GenerateUpgradePlanRequest {
	if in == nil {
		return nil
	}
	out := new(GenerateUpgradePlanRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenerateUpgradePlanRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenerateUpgradePlanResponse) DeepCopyInto(out *GenerateUpgradePlanResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonResponse = in.CommonResponse
	if in.ControlPlaneUpgrades != nil {
		in, out := &in.ControlPlaneUpgrades, &out.ControlPlaneUpgrades
		*out = make([]UpgradeStep, len(*in))
		copy(*out, *in)
	}
	if in.WorkersUpgrades != nil {
		in, out := &in.WorkersUpgrades, &out.WorkersUpgrades
		*out = make([]UpgradeStep, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenerateUpgradePlanResponse.
func (in *GenerateUpgradePlanResponse) DeepCopy() *GenerateUpgradePlanResponse {
	if in == nil {
		return nil
	}
	out := new(GenerateUpgradePlanResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenerateUpgradePlanResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupVersionHook) DeepCopyInto(out *GroupVersionHook) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupVersionHook.
func (in *GroupVersionHook) DeepCopy() *GroupVersionHook {
	if in == nil {
		return nil
	}
	out := new(GroupVersionHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HolderReference) DeepCopyInto(out *HolderReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HolderReference.
func (in *HolderReference) DeepCopy() *HolderReference {
	if in == nil {
		return nil
	}
	out := new(HolderReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineBootstrapBuiltins) DeepCopyInto(out *MachineBootstrapBuiltins) {
	*out = *in
	if in.ConfigRef != nil {
		in, out := &in.ConfigRef, &out.ConfigRef
		*out = new(MachineBootstrapConfigRefBuiltins)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineBootstrapBuiltins.
func (in *MachineBootstrapBuiltins) DeepCopy() *MachineBootstrapBuiltins {
	if in == nil {
		return nil
	}
	out := new(MachineBootstrapBuiltins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineBootstrapConfigRefBuiltins) DeepCopyInto(out *MachineBootstrapConfigRefBuiltins) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineBootstrapConfigRefBuiltins.
func (in *MachineBootstrapConfigRefBuiltins) DeepCopy() *MachineBootstrapConfigRefBuiltins {
	if in == nil {
		return nil
	}
	out := new(MachineBootstrapConfigRefBuiltins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineDeploymentBuiltins) DeepCopyInto(out *MachineDeploymentBuiltins) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(v1beta1.ObjectMeta)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int64)
		**out = **in
	}
	if in.Bootstrap != nil {
		in, out := &in.Bootstrap, &out.Bootstrap
		*out = new(MachineBootstrapBuiltins)
		(*in).DeepCopyInto(*out)
	}
	if in.InfrastructureRef != nil {
		in, out := &in.InfrastructureRef, &out.InfrastructureRef
		*out = new(MachineInfrastructureRefBuiltins)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineDeploymentBuiltins.
func (in *MachineDeploymentBuiltins) DeepCopy() *MachineDeploymentBuiltins {
	if in == nil {
		return nil
	}
	out := new(MachineDeploymentBuiltins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineInfrastructureRefBuiltins) DeepCopyInto(out *MachineInfrastructureRefBuiltins) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineInfrastructureRefBuiltins.
func (in *MachineInfrastructureRefBuiltins) DeepCopy() *MachineInfrastructureRefBuiltins {
	if in == nil {
		return nil
	}
	out := new(MachineInfrastructureRefBuiltins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachinePoolBuiltins) DeepCopyInto(out *MachinePoolBuiltins) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(v1beta1.ObjectMeta)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int64)
		**out = **in
	}
	if in.Bootstrap != nil {
		in, out := &in.Bootstrap, &out.Bootstrap
		*out = new(MachineBootstrapBuiltins)
		(*in).DeepCopyInto(*out)
	}
	if in.InfrastructureRef != nil {
		in, out := &in.InfrastructureRef, &out.InfrastructureRef
		*out = new(MachineInfrastructureRefBuiltins)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachinePoolBuiltins.
func (in *MachinePoolBuiltins) DeepCopy() *MachinePoolBuiltins {
	if in == nil {
		return nil
	}
	out := new(MachinePoolBuiltins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Patch) DeepCopyInto(out *Patch) {
	*out = *in
	if in.Patch != nil {
		in, out := &in.Patch, &out.Patch
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Patch.
func (in *Patch) DeepCopy() *Patch {
	if in == nil {
		return nil
	}
	out := new(Patch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateMachineRequest) DeepCopyInto(out *UpdateMachineRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	in.Desired.DeepCopyInto(&out.Desired)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateMachineRequest.
func (in *UpdateMachineRequest) DeepCopy() *UpdateMachineRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateMachineRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpdateMachineRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateMachineRequestObjects) DeepCopyInto(out *UpdateMachineRequestObjects) {
	*out = *in
	in.Machine.DeepCopyInto(&out.Machine)
	in.InfrastructureMachine.DeepCopyInto(&out.InfrastructureMachine)
	in.BootstrapConfig.DeepCopyInto(&out.BootstrapConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateMachineRequestObjects.
func (in *UpdateMachineRequestObjects) DeepCopy() *UpdateMachineRequestObjects {
	if in == nil {
		return nil
	}
	out := new(UpdateMachineRequestObjects)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateMachineResponse) DeepCopyInto(out *UpdateMachineResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonRetryResponse = in.CommonRetryResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateMachineResponse.
func (in *UpdateMachineResponse) DeepCopy() *UpdateMachineResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateMachineResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpdateMachineResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeStep) DeepCopyInto(out *UpgradeStep) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeStep.
func (in *UpgradeStep) DeepCopy() *UpgradeStep {
	if in == nil {
		return nil
	}
	out := new(UpgradeStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeStepInfo) DeepCopyInto(out *UpgradeStepInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeStepInfo.
func (in *UpgradeStepInfo) DeepCopy() *UpgradeStepInfo {
	if in == nil {
		return nil
	}
	out := new(UpgradeStepInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidateTopologyRequest) DeepCopyInto(out *ValidateTopologyRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]Variable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*ValidateTopologyRequestItem, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ValidateTopologyRequestItem)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidateTopologyRequest.
func (in *ValidateTopologyRequest) DeepCopy() *ValidateTopologyRequest {
	if in == nil {
		return nil
	}
	out := new(ValidateTopologyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValidateTopologyRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidateTopologyRequestItem) DeepCopyInto(out *ValidateTopologyRequestItem) {
	*out = *in
	out.HolderReference = in.HolderReference
	in.Object.DeepCopyInto(&out.Object)
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]Variable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidateTopologyRequestItem.
func (in *ValidateTopologyRequestItem) DeepCopy() *ValidateTopologyRequestItem {
	if in == nil {
		return nil
	}
	out := new(ValidateTopologyRequestItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidateTopologyResponse) DeepCopyInto(out *ValidateTopologyResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonResponse = in.CommonResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidateTopologyResponse.
func (in *ValidateTopologyResponse) DeepCopy() *ValidateTopologyResponse {
	if in == nil {
		return nil
	}
	out := new(ValidateTopologyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValidateTopologyResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Variable) DeepCopyInto(out *Variable) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Variable.
func (in *Variable) DeepCopy() *Variable {
	if in == nil {
		return nil
	}
	out := new(Variable)
	in.DeepCopyInto(out)
	return out
}
