# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 2700s
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'E2_HIGHCPU_8'
steps:
  # The latest image tag + sha can be found with:
  # crane ls registry.k8s.io/releng/gcb-docker-gcloud
  # crane digest registry.k8s.io/releng/gcb-docker-gcloud:v20260806
  - name: 'registry.k8s.io/releng/gcb-docker-gcloud@sha256:b2651f57b579d925a243e308c41546d4fd895f705de091a5a8a39060e6192604' # v20260806
    entrypoint: make
    env:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - TAG=$_GIT_TAG
    - PULL_BASE_REF=$_PULL_BASE_REF
    - DOCKER_BUILDKIT=1
    args:
    - release-staging-nightly
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'dev'
