# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 2700s
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
steps:
  - name: 'gcr.io/k8s-testimages/gcb-docker-gcloud:v20210331-c732583'
    entrypoint: make
    env:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - TAG=$_GIT_TAG
    - PULL_BASE_REF=$_PULL_BASE_REF
    - DOCKER_BUILDKIT=1
    args:
    - release-staging-nightly
  - name: 'gcr.io/k8s-testimages/gcb-docker-gcloud:v20210331-c732583'
    dir: 'test/infrastructure/docker'
    entrypoint: make
    env:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - TAG=$_GIT_TAG
    - PULL_BASE_REF=$_PULL_BASE_REF
    - DOCKER_BUILDKIT=1
    args:
    - release-staging-nightly
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'dev'
