resources:
  - ./rbac.yaml

namespace: observability
namePrefix: capi-

configMapGenerator:
- name: kube-state-metrics-crd-config
  files:
  - capi.yaml=metrics.yaml
  options:
    disableNameSuffixHash: true
    labels:
      kube-state-metrics/custom-resource: "true"
