---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kube-state-metrics/aggregate-to-manager: "true"
  name: manager-metrics-role
rules:
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - clusterresourcesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - kubeadmconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusterclasses
  - clusters
  - machinedeployments
  - machinehealthchecks
  - machinepools
  - machines
  - machinesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kubeadmcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - devclusters
  - devmachines
  - dockerclusters
  - dockermachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - ipaddressclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - runtime.cluster.x-k8s.io
  resources:
  - extensionconfigs
  verbs:
  - get
  - list
  - watch
