# Configuration for prometheus chart, see https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus

# These components do not make sense in a local dev environment
# and can be disabled.
alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: false

server:
  extraFlags:
  # Required for configmap-reload.
  - "web.enable-lifecycle"
  # Used by tempo to write traces.
  - "web.enable-remote-write-receiver"
  persistentVolume:
    # Give Prometheus more space to store metrics.
    size: 20Gi

# Scrape metrics from deployed providers
extraScrapeConfigs: |
  - job_name: 'capi-providers'
    # 15s is a bit often for production but helps to get metrics quicker for development.
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: https
    authorization:
      type: Bearer
      credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - role: pod

    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_labelpresent_cluster_x_k8s_io_provider]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        action: keep
        regex: metrics
      - source_labels: [__meta_kubernetes_pod_label_cluster_x_k8s_io_provider]
        action: replace
        target_label: provider
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
