# Aggregates write access to the kubeadm control plane resources into the builtin "edit" and
# "admin" ClusterRoles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: editor-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kubeadmcontrolplanes
  - kubeadmcontrolplanetemplates
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kubeadmcontrolplanes/scale
  verbs:
  - patch
  - update
