load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["doc.go"],
    importpath = "k8s.io/kube-deploy/ext-apiserver/pkg",
    visibility = ["//visibility:public"],
)
