# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.13.15

# ALERT ################################################################
# This is an unusual dockerfile. The expected build context is all of  #
# cluster api. All paths in this file are relative to cluster-api, not #
# the directory this Dockerfile is in.                                 #
########################################################################

# default the go proxy
ARG goproxy=https://proxy.golang.org

# run this with docker build --build_arg goproxy=$(go env GOPROXY) to override the goproxy
ENV GOPROXY=$goproxy

WORKDIR /tmp
# install a couple of dependencies
RUN curl -L https://dl.k8s.io/v1.14.4/kubernetes-client-linux-amd64.tar.gz | tar xvz
RUN mv /tmp/kubernetes/client/bin/kubectl /usr/local/bin
RUN curl https://get.docker.com | sh

COPY . .
WORKDIR test/infrastructure/docker
RUN go mod download

# Allow containerd to restart pods by calling /restart.sh (mostly for tilt + fast dev cycles)
RUN wget --output-document /restart.sh --quiet https://raw.githubusercontent.com/windmilleng/rerun-process-wrapper/master/restart.sh  && \
    wget --output-document /start.sh --quiet https://raw.githubusercontent.com/windmilleng/rerun-process-wrapper/master/start.sh && \
    chmod +x /start.sh && chmod +x /restart.sh

RUN go build -v -o manager main.go
RUN mv manager /manager

ENTRYPOINT ["/start.sh", "/manager"]
