resources:
  - ../namespace.yaml

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: observability
    valuesFile: values.yaml
    version: 5.5.4

helmGlobals:
    # Store chart in ".charts" folder instead of "charts".
    # Otherwise "go mod tidy" picks up dependencies of go files contained in the Helm Chart.
    # "go mod tidy" ignores folders that begin with ".": https://pkg.go.dev/cmd/go#hdr-Package_lists_and_patterns.
    chartHome: .charts
