{
 "title": "Runtime Extensions",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "hook", "label": "hook", "query": { "query": "label_values(hook)" } }
  ]
 },
 "panels": [
  {
   "title": "Request total",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(capi_runtime_sdk_requests_total{hook=~\"$hook\"}) by (hook)"
    }
   ]
  },
  {
   "title": "Request per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(capi_runtime_sdk_requests_total{hook=~\"$hook\"}[1m])) by (hook)"
    }
   ]
  },
  {
   "title": "Request average duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(capi_runtime_sdk_request_duration_seconds_sum{hook=~\"$hook\"}[5m])) by (hook) / sum(rate(capi_runtime_sdk_request_duration_seconds_count{hook=~\"$hook\"}[5m])) by (hook)"
    }
   ]
  }
 ]
}