{
 "title": "Cluster API Traces",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Span",
    "label": "Span",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_sum,span_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "KCP average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(rate(traces_spanmetrics_latency_sum{span_name!~\"HTTP.*\",span_name!~\"topology.*\",span_name!~\"machine.*\"}[5m]) / rate(traces_spanmetrics_latency_count[5m]))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "KCP 50% percentile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(histogram_quantile(0.50, sum by(le,span_name) (rate(traces_spanmetrics_latency_bucket{span_name=~\"$Span\",span_name!~\"HTTP.*\",span_name!~\"topology.*\",span_name!~\"machine.*\"}[5m])))) > 0.01",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "KCP 90% percentile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(histogram_quantile(0.90, sum by(le,span_name) (rate(traces_spanmetrics_latency_bucket{span_name=~\"$Span\",span_name!~\"HTTP.*\",span_name!~\"topology.*\",span_name!~\"machine.*\"}[5m])))) > 0.01",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "KCP Traces",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(traces_spanmetrics_latency_bucket{span_name=~\"$Span\",span_name!~\"HTTP.*\",span_name!~\"topology.*\",span_name!~\"machine.*\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}