{
 "title": "Cluster API State v1beta2",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# ClusterClass",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(capi_clusterclass_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(capi_cluster_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# KubeadmControlPlane",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(capi_kubeadmcontrolplane_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# MachineDeployment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(capi_machinedeployment_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# MachineSet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(capi_machineset_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# MachinePool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(capi_machinepool_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# Machine",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(capi_machine_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# MachineHealthCheck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(capi_machinehealthcheck_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "targets": [
      { "expr": "sum (capi_cluster_info)", "legendFormat": "All" },
      {
       "expr": "sum(capi_cluster_status_condition_v1beta2{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(capi_cluster_status_condition_v1beta2{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "Cluster by version",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "targets": [
      {
       "expr": "sum (capi_cluster_info) by (topology_version)",
       "legendFormat": "{{topology_version}}"
      }
     ]
    },
    {
     "title": "Cluster by status phase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "targets": [
      {
       "expr": "sum(capi_cluster_status_phase == 1) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    }
   ]
  },
  {
   "title": "KubeadmControlPlane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "KubeadmControlPlane by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum (capi_kubeadmcontrolplane_info)",
       "legendFormat": "All"
      },
      {
       "expr": "sum(capi_kubeadmcontrolplane_status_condition_v1beta2{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(capi_kubeadmcontrolplane_status_condition_v1beta2{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "KubeadmControlPlane by version",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
     "targets": [
      {
       "expr": "sum (capi_kubeadmcontrolplane_info) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "KubeadmControlPlane replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum (capi_kubeadmcontrolplane_spec_replicas)",
       "legendFormat": "spec replicas"
      },
      {
       "expr": "sum (capi_kubeadmcontrolplane_status_replicas)",
       "legendFormat": "status replicas"
      },
      {
       "expr": "sum (capi_kubeadmcontrolplane_status_replicas_ready)",
       "legendFormat": "status ready replicas"
      },
      {
       "expr": "sum (capi_kubeadmcontrolplane_status_replicas_unavailable)",
       "legendFormat": "status unavailable replicas"
      },
      {
       "expr": "sum (capi_kubeadmcontrolplane_status_replicas_uptodate)",
       "legendFormat": "status up-to-date replicas"
      }
     ]
    }
   ]
  },
  {
   "title": "MachineDeployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "MachineDeployment by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum (capi_machinedeployment_info)",
       "legendFormat": "All"
      },
      {
       "expr": "sum(capi_machinedeployment_status_condition_v1beta2{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(capi_machinedeployment_status_condition_v1beta2{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "MachineDeployment by version",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
     "targets": [
      {
       "expr": "sum (capi_machinedeployment_info) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "MachineDeployment replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum (capi_machinedeployment_spec_replicas)",
       "legendFormat": "spec replicas"
      },
      {
       "expr": "sum (capi_machinedeployment_status_replicas)",
       "legendFormat": "status replicas"
      },
      {
       "expr": "sum (capi_machinedeployment_status_replicas_ready)",
       "legendFormat": "status ready replicas"
      },
      {
       "expr": "sum (capi_machinedeployment_status_replicas_unavailable)",
       "legendFormat": "status unavailable replicas"
      },
      {
       "expr": "sum (capi_machinedeployment_status_replicas_uptodate)",
       "legendFormat": "status up-to-date replicas"
      },
      {
       "expr": "sum (capi_machinedeployment_status_replicas_available)",
       "legendFormat": "status available replicas"
      }
     ]
    },
    {
     "title": "MachineDeployment by status phase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
     "targets": [
      {
       "expr": "sum(capi_machinedeployment_status_phase == 1) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MachineSet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "MachineSet by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "targets": [
      { "expr": "sum (capi_machineset_info)", "legendFormat": "All" },
      {
       "expr": "sum(capi_machineset_status_condition_v1beta2{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(capi_machineset_status_condition_v1beta2{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "MachineSet by version",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "expr": "sum (capi_machineset_info) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "MachineSet replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum (capi_machineset_spec_replicas)",
       "legendFormat": "spec replicas"
      },
      {
       "expr": "sum (capi_machineset_status_replicas)",
       "legendFormat": "status replicas"
      },
      {
       "expr": "sum (capi_machineset_status_replicas_ready)",
       "legendFormat": "status ready replicas"
      },
      {
       "expr": "sum (capi_machineset_status_replicas_available)",
       "legendFormat": "status available replicas"
      },
      {
       "expr": "sum (capi_machineset_status_replicas_fully_labeled)",
       "legendFormat": "status fully labeled replicas"
      }
     ]
    }
   ]
  },
  {
   "title": "MachinePool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "MachinePool by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "targets": [
      { "expr": "sum (capi_machinepool_info)", "legendFormat": "All" },
      {
       "expr": "sum(capi_machinepool_status_condition_v1beta2{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(capi_machinepool_status_condition_v1beta2{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "MachinePool by version",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "targets": [
      {
       "expr": "sum (capi_machinepool_info) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "MachinePool replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum (capi_machinepool_spec_replicas)",
       "legendFormat": "spec replicas"
      },
      {
       "expr": "sum (capi_machinepool_status_replicas)",
       "legendFormat": "status replicas"
      },
      {
       "expr": "sum (capi_machinepool_status_replicas_ready)",
       "legendFormat": "status ready replicas"
      },
      {
       "expr": "sum (capi_machinepool_status_replicas_unavailable)",
       "legendFormat": "status unavailable replicas"
      },
      {
       "expr": "sum (capi_machinepool_status_replicas_available)",
       "legendFormat": "status available replicas"
      }
     ]
    },
    {
     "title": "MachinePool by status phase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "targets": [
      {
       "expr": "sum(capi_machinepool_status_phase == 1) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Control Plane Machine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Control Plane Machine by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(capi_machine_info{control_plane_name!=\"\"})",
       "legendFormat": "All"
      },
      {
       "expr": "sum(avg(capi_machine_info{control_plane_name!=\"\"}) by (name) * on(name) group_right () (capi_machine_status_condition_v1beta2{status=\"True\"} == 1)) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(avg(capi_machine_info{control_plane_name!=\"\"}) by (name) * on(name) group_right () (capi_machine_status_condition_v1beta2{status=\"False\"} == 1)) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "Control Plane Machine by version",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "targets": [
      {
       "expr": "sum (capi_machine_info{control_plane_name!=\"\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Control Plane Machine by status phase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
     "targets": [
      {
       "expr": "sum(avg(capi_machine_info{control_plane_name!=\"\"}) by (name) * on (name) group_right () (capi_machine_status_phase == 1)) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker Machine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker Machine by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(capi_machine_info{control_plane_name=\"\"})",
       "legendFormat": "All"
      },
      {
       "expr": "sum(avg(capi_machine_info{control_plane_name=\"\"}) by (name) * on(name) group_right () (capi_machine_status_condition_v1beta2{status=\"True\"} == 1)) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(avg(capi_machine_info{control_plane_name=\"\"}) by (name) * on(name) group_right () (capi_machine_status_condition_v1beta2{status=\"False\"} == 1)) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "Worker Machine by version",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "targets": [
      {
       "expr": "sum (capi_machine_info{control_plane_name=\"\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Worker Machine by status phase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
     "targets": [
      {
       "expr": "sum(avg(capi_machine_info{control_plane_name=\"\"}) by (name) * on (name) group_right () (capi_machine_status_phase == 1)) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MachineHealthCheck",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "MachineHealthCheck by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum (capi_machinehealthcheck_info)",
       "legendFormat": "All"
      },
      {
       "expr": "sum(capi_machinehealthcheck_status_condition_v1beta2{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(capi_machinehealthcheck_status_condition_v1beta2{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "MachineHealthCheck replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum (capi_machinehealthcheck_status_expected_machines)",
       "legendFormat": "status expected"
      },
      {
       "expr": "sum (capi_machinehealthcheck_status_current_healthy)",
       "legendFormat": "status current healthy"
      }
     ]
    }
   ]
  }
 ]
}