{
 "title": "Cluster API Performance v1beta2",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# ClusterClass",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(capi_clusterclass_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(capi_cluster_info{name=~\"${Cluster:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# KubeadmControlPlane",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(capi_kubeadmcontrolplane_info{cluster_name=~\"${Cluster:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# MachineDeployment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(capi_machinedeployment_info{cluster_name=~\"${Cluster:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# MachineSet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(capi_machineset_info{cluster_name=~\"${Cluster:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# MachinePool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(capi_machinepool_info{cluster_name=~\"${Cluster:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Machine",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(capi_machine_info{cluster_name=~\"${Cluster:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# MachineHealthCheck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(capi_machinehealthcheck_info{cluster_name=~\"${Cluster:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster time until last Machine NodeHealthy since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(capi_cluster_created{name=~\"${Cluster:pipe}\"}, \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\")) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cluster time until InfrastructureReady since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"InfrastructureReady\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cluster time until ControlPlaneReady since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"ControlPlaneReady\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"InfrastructureReady\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"})",
       "legendFormat": "until InfrastructureReady since creationTimestamp"
      },
      {
       "expr": "avg(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"ControlPlaneReady\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"})",
       "legendFormat": "until ControlPlaneReady since creationTimestamp"
      },
      {
       "expr": "avg(label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(capi_cluster_created{name=~\"${Cluster:pipe}\"}, \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\"))",
       "legendFormat": "until last Machine NodeHealthy since creationTimestamp"
      }
     ]
    },
    {
     "title": "Cluster overview",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"InfrastructureReady\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"ControlPlaneReady\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(capi_cluster_created{name=~\"${Cluster:pipe}\"}, \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\")) by (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(capi_cluster_info{name=~\"${Cluster:pipe}\"} * on(name) group_right () label_replace(capi_machine_info{control_plane_name!=\"\"}, \"name\", \"$0\", \"cluster_name\", \".*\")) by(name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(capi_cluster_info{name=~\"${Cluster:pipe}\"} * on(name) group_right () label_replace(capi_machine_info{control_plane_name=\"\"}, \"name\", \"$0\", \"cluster_name\", \".*\")) by(name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (name) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cluster time until condition first true since creationTimestamp (all)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Cluster time until condition first true since creationTimestamp (last 5m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg((min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h])>= time() - 60*5) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Cluster time until last Machine NodeHealthy since creationTimestamp (all)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(capi_cluster_created{name=~\"${Cluster:pipe}\"}, \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name))",
       "legendFormat": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "KubeadmControlPlane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "KubeadmControlPlane time until Ready since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_kubeadmcontrolplane_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"Ready\"}[168h]) - on(name) group_left () capi_kubeadmcontrolplane_created{cluster_name=~\"${Cluster:pipe}\"}) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average time until Ready since creationTimestamp",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_kubeadmcontrolplane_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"Ready\"}[168h]) - on(name) group_left () capi_kubeadmcontrolplane_created{cluster_name=~\"${Cluster:pipe}\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "KubeadmControlPlane overview",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_kubeadmcontrolplane_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"Ready\"}[168h]) - on(name) group_left () capi_kubeadmcontrolplane_created{cluster_name=~\"${Cluster:pipe}\"}) by (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(capi_kubeadmcontrolplane_created{cluster_name=~\"${Cluster:pipe}\"}) by (name) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "KubeadmControlPlane time until condition first true since creationTimestamp (all)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_kubeadmcontrolplane_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () capi_kubeadmcontrolplane_created{cluster_name=~\"${Cluster:pipe}\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KubeadmControlPlane time until condition first true since creationTimestamp (last 5m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg((min_over_time(capi_kubeadmcontrolplane_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h])>= time() - 60*5) - on(name) group_left () capi_kubeadmcontrolplane_created{cluster_name=~\"${Cluster:pipe}\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Control Plane Machine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Control Plane Machine time until NodeHealthy since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name!=\"\"}) by (name))) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Control Plane Machine time until BootstrapReady since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"BootstrapReady\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name!=\"\"}) by (name))) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Control Plane Machine time until InfrastructureReady since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"InfrastructureReady\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name!=\"\"}) by (name))) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"BootstrapReady\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name!=\"\"}) by (name)))",
       "legendFormat": "until BootstrapReady since creationTimestamp"
      },
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"InfrastructureReady\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name!=\"\"}) by (name)))",
       "legendFormat": "until InfrastructureReady since creationTimestamp"
      },
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name!=\"\"}) by (name)))",
       "legendFormat": "until NodeHealthy since creationTimestamp"
      }
     ]
    },
    {
     "title": "Control Plane Machines Overview",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"BootstrapReady\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name!=\"\"}) by (name))) by (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"InfrastructureReady\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name!=\"\"}) by (name))) by (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name!=\"\"}) by (name))) by (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right capi_machine_info{control_plane_name!=\"\"}) by (name) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Control Plane Machine time until condition first true since creationTimestamp (all)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name!=\"\"}) by (name))) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Control Plane Machine time until condition first true since creationTimestamp (last 5m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg((min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h])>= time() - 60*5) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name!=\"\"}) by (name))) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker Machine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker Machine time until NodeHealthy since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name=\"\"}) by (name))) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Worker Machine time until BootstrapReady since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"BootstrapReady\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name=\"\"}) by (name))) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Worker Machine time until InfrastructureReady since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"InfrastructureReady\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name=\"\"}) by (name))) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"BootstrapReady\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name=\"\"}) by (name)))",
       "legendFormat": "until BootstrapReady since creationTimestamp"
      },
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"InfrastructureReady\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name=\"\"}) by (name)))",
       "legendFormat": "until InfrastructureReady since creationTimestamp"
      },
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name=\"\"}) by (name)))",
       "legendFormat": "until NodeHealthy since creationTimestamp"
      }
     ]
    },
    {
     "title": "Worker Machines Overview",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"BootstrapReady\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name=\"\"}) by (name))) by (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"InfrastructureReady\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name=\"\"}) by (name))) by (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name=\"\"}) by (name))) by (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right capi_machine_info{control_plane_name=\"\"}) by (name) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Worker Machine time until condition first true since creationTimestamp (all)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name=\"\"}) by (name))) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Worker Machine time until condition first true since creationTimestamp (last 5m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg((min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h])>= time() - 60*5) - on(name) group_left () (capi_machine_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right avg(capi_machine_info{control_plane_name=\"\"}) by (name))) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Control Plane KubeadmConfig",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Control Plane KubeadmConfig time until Ready since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_kubeadmconfig_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"Ready\"}[168h]) - on(name) group_left () (capi_kubeadmconfig_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right ()  (avg(label_replace(capi_machine_info{control_plane_name!=\"\"}, \"name\", \"$0\", \"bootstrap_reference_name\", \".*\")) by (name)))) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average time until Ready since creationTimestamp",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_kubeadmconfig_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"Ready\"}[168h]) - on(name) group_left () (capi_kubeadmconfig_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right ()  (avg(label_replace(capi_machine_info{control_plane_name!=\"\"}, \"name\", \"$0\", \"bootstrap_reference_name\", \".*\")) by (name))))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Control Plane KubeadmConfig Overview",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_kubeadmconfig_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"Ready\"}[168h]) - on(name) group_left () (capi_kubeadmconfig_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right ()  (avg(label_replace(capi_machine_info{control_plane_name!=\"\"}, \"name\", \"$0\", \"bootstrap_reference_name\", \".*\")) by (name)))) by (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(capi_kubeadmconfig_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right ()  (avg(label_replace(capi_machine_info{control_plane_name!=\"\"}, \"name\", \"$0\", \"bootstrap_reference_name\", \".*\")) by (name))) by (name) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Control Plane KubeadmConfig time until condition first true since creationTimestamp (all)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_kubeadmconfig_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () (capi_kubeadmconfig_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right ()  (avg(label_replace(capi_machine_info{control_plane_name!=\"\"}, \"name\", \"$0\", \"bootstrap_reference_name\", \".*\")) by (name)))) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Control Plane KubeadmConfig time until condition first true since creationTimestamp (last 5m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg((min_over_time(capi_kubeadmconfig_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h])>= time() - 60*5) - on(name) group_left () (capi_kubeadmconfig_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right ()  (avg(label_replace(capi_machine_info{control_plane_name!=\"\"}, \"name\", \"$0\", \"bootstrap_reference_name\", \".*\")) by (name)))) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker KubeadmConfig",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker KubeadmConfig time until Ready since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_kubeadmconfig_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"Ready\"}[168h]) - on(name) group_left () (capi_kubeadmconfig_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right ()  (avg(label_replace(capi_machine_info{control_plane_name=\"\"}, \"name\", \"$0\", \"bootstrap_reference_name\", \".*\")) by (name)))) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average time until Ready since creationTimestamp",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_kubeadmconfig_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"Ready\"}[168h]) - on(name) group_left () (capi_kubeadmconfig_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right ()  (avg(label_replace(capi_machine_info{control_plane_name=\"\"}, \"name\", \"$0\", \"bootstrap_reference_name\", \".*\")) by (name))))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Worker KubeadmConfig Overview",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_kubeadmconfig_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"Ready\"}[168h]) - on(name) group_left () (capi_kubeadmconfig_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right ()  (avg(label_replace(capi_machine_info{control_plane_name=\"\"}, \"name\", \"$0\", \"bootstrap_reference_name\", \".*\")) by (name)))) by (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(capi_kubeadmconfig_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right ()  (avg(label_replace(capi_machine_info{control_plane_name=\"\"}, \"name\", \"$0\", \"bootstrap_reference_name\", \".*\")) by (name))) by (name) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Worker KubeadmConfig time until condition first true since creationTimestamp (all)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(min_over_time(capi_kubeadmconfig_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () (capi_kubeadmconfig_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right ()  (avg(label_replace(capi_machine_info{control_plane_name=\"\"}, \"name\", \"$0\", \"bootstrap_reference_name\", \".*\")) by (name)))) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Worker KubeadmConfig time until condition first true since creationTimestamp (last 5m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg((min_over_time(capi_kubeadmconfig_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h])>= time() - 60*5) - on(name) group_left () (capi_kubeadmconfig_created{cluster_name=~\"${Cluster:pipe}\"} * on (name) group_right ()  (avg(label_replace(capi_machine_info{control_plane_name=\"\"}, \"name\", \"$0\", \"bootstrap_reference_name\", \".*\")) by (name)))) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "KPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Time until Condition true since creationTimestamp",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "min(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (type)"
      },
      {
       "expr": "max(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"})  by (type)"
      },
      {
       "expr": "avg(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"})  by (type)"
      },
      {
       "expr": "quantile(0.5, min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"})  by (type)"
      },
      {
       "expr": "quantile(0.9, min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (type)"
      },
      {
       "expr": "quantile(0.99, min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (type)"
      },
      {
       "expr": "stddev(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (type)"
      },
      {
       "expr": "avg(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () bottomk(10, avg(capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (name))) by (type)"
      },
      {
       "expr": "avg(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () topk(10, avg(capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (name))) by (type)\n"
      },
      {
       "expr": "(avg(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () topk(10, avg(capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (name))) by (type) - avg(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () bottomk(10, avg(capi_cluster_created) by (name))) by (type)) / avg(min_over_time(capi_cluster_status_condition_v1beta2_last_transition_time{status=\"True\"}[168h]) - on(name) group_left () bottomk(10, avg(capi_cluster_created) by (name))) by (type)\n"
      }
     ]
    },
    {
     "title": "Cluster time until last Machine NodeHealthy since creationTimestamp",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "min(label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(capi_cluster_created{name=~\"${Cluster:pipe}\"}, \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\"))"
      },
      {
       "expr": "max(label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(capi_cluster_created{name=~\"${Cluster:pipe}\"}, \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\"))"
      },
      {
       "expr": "avg(label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(capi_cluster_created{name=~\"${Cluster:pipe}\"}, \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\"))"
      },
      {
       "expr": "quantile(0.5, label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(capi_cluster_created{name=~\"${Cluster:pipe}\"}, \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\"))"
      },
      {
       "expr": "quantile(0.9, label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(capi_cluster_created{name=~\"${Cluster:pipe}\"}, \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\"))"
      },
      {
       "expr": "quantile(0.99, label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(capi_cluster_created{name=~\"${Cluster:pipe}\"}, \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\"))"
      },
      {
       "expr": "avg(label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(bottomk(10, avg(capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (name)), \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\"))"
      },
      {
       "expr": "avg(label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(topk(10, avg(capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (name)), \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\"))"
      },
      {
       "expr": "(avg(label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(topk(10, avg(capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (name)), \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\")) - avg(label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(bottomk(10, avg(capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (name)), \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\"))) / avg(label_replace(max(min_over_time(capi_machine_status_condition_v1beta2_last_transition_time{status=\"True\",type=\"NodeHealthy\"}[168h])) by (cluster_name) - on (cluster_name) label_replace(bottomk(10, avg(capi_cluster_created{name=~\"${Cluster:pipe}\"}) by (name)), \"cluster_name\", \"$0\", \"name\", \".*\") unless count(capi_machine_status_condition_v1beta2_last_transition_time{status=\"False\",type=\"NodeHealthy\"}) by (cluster_name), \"name\", \"$0\", \"cluster_name\", \".*\"))"
      }
     ]
    }
   ]
  }
 ]
}