name: ❄️ Flaking Test
description: Report flaky tests or jobs in Cluster API CI
body:
  - type: textarea
    id: jobs
    attributes:
      label: Which jobs are flaking?
      description: |
        Please only use this template for submitting reports about flaky tests or jobs (pass or fail with no underlying change in code) in Cluster API CI.
        Links to go.k8s.io/triage and/or links to specific failures in spyglass are appreciated.
    validations:
      required: true

  - type: textarea
    id: tests
    attributes:
      label: Which tests are flaking?
    validations:
      required: true

  - type: textarea
    id: since
    attributes:
      label: Since when has it been flaking?
    validations:
      required: true

  - type: input
    id: testgrid
    attributes:
      label: Testgrid link

  - type: textarea
    id: reason
    attributes:
      label: Reason for failure (if possible)

  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?
      placeholder: "Miscellaneous information that will assist in fixing the flaking test."

  - type: textarea
    id: templateLabel
    attributes:
      label: Label(s) to be applied
      value: |
        /kind flake
        One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.