@startuml
:MachinePool infrastructure reference has changed;
if (status.InfrastructureSelector exists) then (no)
    :create and delete Machines owned by the MachinePool to match replica count
     with no infraMachineRef;
else (yes)
    :Find the infrastructure resources defined by the selector, API version, and kind;
    repeat :infraMachineRef as Infrastructure Machine Reference
        :create a Machine owned by the MachinePool
        :set ownership of the infrastructure machine to the newly created Machine;
    repeat while (more infraMachineRefs)
    :delete Machines which don't own infrastructure resources found by the selector
        Clean up after instances that no longer exist;
endif
:continue reconciling MachinePool...;
stop
@enduml
