@startuml
title Figure 8: User creates a machine with kubeadm bootstrapper

' -- GROUPS START ---

box #lightgreen
participant "API Server"
end box

box #lightblue
participant "Cluster API Machine Controller"
end box

box #lightgreen
participant "Workload Cluster API Server"
end box

' -- GROUPS END ---


"API Server"-->>"Cluster API Machine Controller": AWSInfrastructureConfig updated

"Cluster API Machine Controller"-> "Cluster API Machine Controller":Machine Controller Reconcile
activate "Cluster API Machine Controller"

note over "Cluster API Machine Controller": - ✅ Machine.Status.Phase is "Provisioned" \n- ✅ Machine.Spec.InfrastructureRef -> Status.Ready is true\n- ✅ Machine.Spec.InfrastructureRef -> Status.Addresses is not empty

loop until timeout or Node's status is Ready
"Cluster API Machine Controller"->"Workload Cluster API Server": Get Node
"Cluster API Machine Controller"<<--"Workload Cluster API Server": Response
note over "Cluster API Machine Controller":Loop conditions:\n- ✅ Node.Spec.ProviderID matches Machine.Spec.ProviderID\n- ✅ Node status is "Ready"
end

"Cluster API Machine Controller"->"Cluster API Machine Controller": Set Machine.Status.NodeRef

"Cluster API Machine Controller"->"Cluster API Machine Controller": Set Machine.Status.Phase to "Ready"

"Cluster API Machine Controller"->"API Server": Update Machine
"Cluster API Machine Controller"<--"API Server": Response

deactivate "Cluster API Machine Controller"

hide footbox
@enduml
