apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: quick-start
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.128.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    classRef:
      name: quick-start
    controlPlane:
      replicas: 3
    variables:
    - name: imageRepository
      value: ""
    - name: etcdImageTag
      value: "3.6.4-0"
    - name: coreDNSImageTag
      value: ""
    - name: podSecurityStandard
      value:
        enabled: true
        enforce: "baseline"
        audit: "restricted"
        warn: "restricted"
    version: v1.33.4
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 1
---
