  - groupVersionKind:
      group: cluster.x-k8s.io
      kind: MachineSet
      version: v1beta1
    labelsFromPath:
      cluster_name:
      - spec
      - clusterName
      name:
      - metadata
      - name
      namespace:
      - metadata
      - namespace
      uid:
      - metadata
      - uid
    metricNamePrefix: capi_machineset
    metrics:
    - name: info
      help: Information about a machineset.
      each:
        info:
          labelsFromPath:
            version:
            - spec
            - template
            - spec
            - version
            bootstrap_reference_kind:
            - spec
            - template
            - spec
            - bootstrap
            - configRef
            - kind
            bootstrap_reference_name:
            - spec
            - template
            - spec
            - bootstrap
            - configRef
            - name
            infrastructure_reference_kind:
            - spec
            - template
            - spec
            - infrastructureRef
            - kind
            infrastructure_reference_name:
            - spec
            - template
            - spec
            - infrastructureRef
            - name
        type: Info
    - name: spec_replicas
      help: The number of desired machines for a machineset.
      each:
        gauge:
          path:
          - spec
          - replicas
          nilIsZero: true
        type: Gauge
    - name: status_replicas_available
      help: The number of available replicas per machineset.
      each:
        gauge:
          path:
          - status
          - availableReplicas
          nilIsZero: true
        type: Gauge
    - name: status_replicas_fully_labeled
      help: The number of fully labeled replicas per machineset.
      each:
        gauge:
          path:
          - status
          - fullyLabeledReplicas
        type: Gauge
    - name: status_replicas_ready
      help: The number of ready replicas per machineset.
      each:
        gauge:
          path:
          - status
          - readyReplicas
          nilIsZero: true
        type: Gauge
    - name: status_replicas
      help: The number of replicas per machineset.
      each:
        gauge:
          path:
          - status
          - replicas
          nilIsZero: true
        type: Gauge
