namespace: capi-kubeadm-control-plane-system

namePrefix: capi-kubeadm-control-plane-

commonLabels:
  cluster.x-k8s.io/provider: "control-plane-kubeadm"

bases:
  - ../../../controlplane/kubeadm/config/manager

patchesStrategicMerge:
  - ../../../controlplane/kubeadm/config/default/manager_image_patch.yaml
  - ../../../controlplane/kubeadm/config/default/manager_pull_policy.yaml

patchesJson6902:
  - target:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: system
      version: v1
    path: patch_service_account.yaml
  - target:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: system
      version: v1
    path: patch_healthcheck.yaml

