apiVersion: v1
kind: ConfigMap
metadata:
  name: headlamp-kubeconfig
  namespace: observability
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://kubernetes.default.svc
      name: local
    contexts:
    - context:
        cluster: local
        user: headlamp
      name: local
    current-context: local
    users:
    - name: headlamp
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
