@startuml cluster-admission-machineset-controller

start;
:MachineSet controller;

repeat
  :MachineSet controller enqueues a Reconcile call;
  :List machines specified by selector;
  repeat
    if (Machine has no controller) then (yes)
      #LightBlue:Adopt machine;
    endif
  repeat while (More machines) is (yes)
  if (Not enough replicas) then (yes)
    #LightBlue:Boot new machine;
  elseif (Too many replicas) then (yes)
    #LightBlue:Delete machines;
  endif
  if (Not all machines are ready) then (yes)
    #Pink:Return Requeue;
  endif
repeat while (Create returned Requeue) is (yes)
stop;

@enduml