resources:
  - ../namespace.yaml
  # The grafana helm chart will reference a configmap with name `grafana-dashboards`.
  # The configMapGenerator below will create the configmap and append a hash suffix calculated from its
  # content to the name. Kustomize will append the suffix hash to all references in the helm chart, but
  # only when the helm chart content is referenced in "resources".
  # This would not work if the helm chart is configured in this file via the "helmCharts" option.
  - ./chart

namespace: observability

configMapGenerator:
- name: grafana-dashboard-cluster-api-mgmt-apiserver-requests
  files:
  - dashboards/cluster-api-mgmt-apiserver-requests.json
- name: grafana-dashboard-cluster-api-performance
  files:
  - dashboards/cluster-api-performance.json
- name: grafana-dashboard-cluster-api-state
  files:
  - dashboards/cluster-api-state.json
- name: grafana-dashboard-cluster-api-wl-apiserver-requests
  files:
  - dashboards/cluster-api-wl-apiserver-requests.json
- name: grafana-dashboard-controller-runtime
  files:
  - dashboards/controller-runtime.json
- name: grafana-dashboard-runtime-extensions
  files:
  - dashboards/runtime-extensions.json
