# Configuration for grafana chart, see https://github.com/grafana/helm-charts/tree/main/charts/grafana

grafana.ini:
  # Disable the grafana login form.
  auth:
    disable_login_form: true
  # Enable anonymous user, and set them as part of the default org.
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Admin
  feature_toggles:
    enable: "tempoSearch tempoBackendSearch"

# Adds loki as a datasource.
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    # https://grafana.com/docs/grafana/latest/datasources/loki/
    - name: Loki
      type: loki
      uid: loki
      orgId: 1
      url: http://loki:3100
      isDefault: true
      editable: true
      jsonData:
        maxLines: 1000
        derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceID":"(\w+)"'
          name: TraceID
          url: $${__value.raw}
          urlDisplayLabel: Trace
    # https://grafana.com/docs/grafana/latest/datasources/prometheus/
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://prometheus-server
      editable: true
      jsonData:
        httpMethod: 'GET'
        exemplarTraceIDDestination:
          name: 'traceID'
          url: 'http://localhost:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22tempo%22,%7B%22query%22:%22$${value}%22%7D%5D'
    # https://grafana.com/docs/grafana/latest/datasources/tempo/
    - name: Tempo
      type: tempo
      uid: tempo
      url: http://tempo:3100
      editable: true
      jsonData:
        tracesToLogs:
          datasourceUid: 'loki'
          tags: [ 'app' ]
          spanEndTimeShift: 1h
          spanStartTimeShift: -1h
          filterByTraceID: true
          filterBySpanID: false
          lokiSearch: true

        serviceMap:
          datasourceUid: 'prometheus'
        search:
          hide: false
        nodeGraph:
          enabled: true

# Disable grafana test framework
testFramework:
  enabled: false
