apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: "my-cluster"
  namespace: namespace-one
  labels:
    cni: kindnet
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.128.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    classRef:
      name: my-cluster-class
    version: v1.21.2
    controlPlane:
      metadata: {}
      replicas: 1
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: "my-second-cluster"
  namespace: namespace-two
  labels:
    cni: kindnet
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.128.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    classRef:
      name: my-second-cluster-class
    version: v1.21.2
    controlPlane:
      metadata: {}
      replicas: 1
