/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package conversion

import (
	"context"

	"sigs.k8s.io/controller-runtime/pkg/webhook/conversion"

	clusterv1beta1 "sigs.k8s.io/cluster-api/api/core/v1beta1"
	clusterv1 "sigs.k8s.io/cluster-api/api/core/v1beta2"
	ipamv1alpha1 "sigs.k8s.io/cluster-api/api/ipam/v1alpha1"
	ipamv1beta1 "sigs.k8s.io/cluster-api/api/ipam/v1beta1"
	ipamv1 "sigs.k8s.io/cluster-api/api/ipam/v1beta2"
	conversionutil "sigs.k8s.io/cluster-api/util/conversion"
)

// IPAddressClaim is a HubSpokeConverter for the IPAddressClaim API type.
var IPAddressClaim = conversion.NewHubSpokeConverter(&ipamv1.IPAddressClaim{},
	conversion.NewSpokeConverter(&ipamv1alpha1.IPAddressClaim{}, ConvertIPAddressClaimHubToV1Alpha1, ConvertIPAddressClaimV1Alpha1ToHub),
	conversion.NewSpokeConverter(&ipamv1beta1.IPAddressClaim{}, ConvertIPAddressClaimHubToV1Beta1, ConvertIPAddressClaimV1Beta1ToHub),
)

// ConvertIPAddressClaimV1Alpha1ToHub converts a v1alpha1 IPAddressClaim to a hub IPAddressClaim.
func ConvertIPAddressClaimV1Alpha1ToHub(_ context.Context, src *ipamv1alpha1.IPAddressClaim, dst *ipamv1.IPAddressClaim) error {
	if err := ipamv1alpha1.Convert_v1alpha1_IPAddressClaim_To_v1beta2_IPAddressClaim(src, dst, nil); err != nil {
		return err
	}

	// Reset conditions from autogenerated conversions
	// NOTE: v1beta1 conditions should not be automatically be converted into v1beta2 conditions.
	dst.Status.Conditions = nil

	// Move legacy conditions (v1beta1) to the deprecated field.
	if src.Status.Conditions != nil {
		dst.Status.Deprecated = &ipamv1.IPAddressClaimDeprecatedStatus{}
		dst.Status.Deprecated.V1Beta1 = &ipamv1.IPAddressClaimV1Beta1DeprecatedStatus{}
		clusterv1beta1.Convert_v1beta1_Conditions_To_v1beta2_Deprecated_V1Beta1_Conditions(&src.Status.Conditions, &dst.Status.Deprecated.V1Beta1.Conditions)
	}

	if src.Labels != nil {
		dst.Spec.ClusterName = src.Labels[clusterv1.ClusterNameLabel]
		if dst.Annotations != nil {
			if clusterNameLabelWasSet, ok := dst.Annotations["conversion.cluster.x-k8s.io/cluster-name-label-set"]; ok {
				if clusterNameLabelWasSet == "false" {
					delete(dst.Labels, clusterv1.ClusterNameLabel)
				}
				delete(dst.Annotations, "conversion.cluster.x-k8s.io/cluster-name-label-set")
			}
		}
	}

	// Manually restore data.
	restored := &ipamv1.IPAddressClaim{}
	if ok, err := conversionutil.UnmarshalData(src, restored); err != nil || !ok {
		return err
	}
	dst.Status.Conditions = restored.Status.Conditions

	return nil
}

// ConvertIPAddressClaimHubToV1Alpha1 converts a hub IPAddressClaim to a v1alpha1 IPAddressClaim.
func ConvertIPAddressClaimHubToV1Alpha1(_ context.Context, src *ipamv1.IPAddressClaim, dst *ipamv1alpha1.IPAddressClaim) error {
	if err := ipamv1alpha1.Convert_v1beta2_IPAddressClaim_To_v1alpha1_IPAddressClaim(src, dst, nil); err != nil {
		return err
	}

	// Reset conditions from autogenerated conversions
	// NOTE: v1beta2 conditions should not be automatically be converted into legacy conditions (v1beta1).
	dst.Status.Conditions = nil

	// Retrieve legacy conditions (v1beta1) from the deprecated field.
	if src.Status.Deprecated != nil {
		if src.Status.Deprecated.V1Beta1 != nil {
			if src.Status.Deprecated.V1Beta1.Conditions != nil {
				clusterv1beta1.Convert_v1beta2_Deprecated_V1Beta1_Conditions_To_v1beta1_Conditions(&src.Status.Deprecated.V1Beta1.Conditions, &dst.Status.Conditions)
			}
		}
	}

	if src.Spec.ClusterName != "" {
		if dst.Labels == nil {
			dst.Labels = map[string]string{}
		}
		if _, ok := dst.Labels[clusterv1.ClusterNameLabel]; !ok {
			if dst.Annotations == nil {
				dst.Annotations = map[string]string{}
			}
			dst.Annotations["conversion.cluster.x-k8s.io/cluster-name-label-set"] = "false"
		}
		dst.Labels[clusterv1.ClusterNameLabel] = src.Spec.ClusterName
	}

	// Preserve Hub data on down-conversion except for metadata
	return conversionutil.MarshalDataUnsafeNoCopy(src, dst)
}

// ConvertIPAddressClaimV1Beta1ToHub converts a v1beta1 IPAddressClaim to a hub IPAddressClaim.
func ConvertIPAddressClaimV1Beta1ToHub(_ context.Context, src *ipamv1beta1.IPAddressClaim, dst *ipamv1.IPAddressClaim) error {
	return ipamv1beta1.Convert_v1beta1_IPAddressClaim_To_v1beta2_IPAddressClaim(src, dst, nil)
}

// ConvertIPAddressClaimHubToV1Beta1 converts a hub IPAddressClaim to a v1beta1 IPAddressClaim.
func ConvertIPAddressClaimHubToV1Beta1(_ context.Context, src *ipamv1.IPAddressClaim, dst *ipamv1beta1.IPAddressClaim) error {
	return ipamv1beta1.Convert_v1beta2_IPAddressClaim_To_v1beta1_IPAddressClaim(src, dst, nil)
}
