name: Weekly security scan

on:
  schedule:
    # Cron for every Monday at 12:00 UTC.
    - cron: "0 12 * * 1"

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  scan:
    strategy:
      fail-fast: false
      matrix:
        branch: [ main, release-1.13, release-1.12 ]
    name: Trivy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
      with:
        ref: ${{ matrix.branch }}
        persist-credentials: false
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # tag=v7.0.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Run verify security target
      run: make verify-security
