//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIEndpoint) DeepCopyInto(out *APIEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIEndpoint.
func (in *APIEndpoint) DeepCopy() *APIEndpoint {
	if in == nil {
		return nil
	}
	out := new(APIEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerCluster) DeepCopyInto(out *DockerCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerCluster.
func (in *DockerCluster) DeepCopy() *DockerCluster {
	if in == nil {
		return nil
	}
	out := new(DockerCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterList) DeepCopyInto(out *DockerClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DockerCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterList.
func (in *DockerClusterList) DeepCopy() *DockerClusterList {
	if in == nil {
		return nil
	}
	out := new(DockerClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterSpec) DeepCopyInto(out *DockerClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make(apiv1beta1.FailureDomains, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	out.LoadBalancer = in.LoadBalancer
	if in.Subnets1 != nil {
		in, out := &in.Subnets1, &out.Subnets1
		*out = make(DockerClusterSubnets1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Subnets2 != nil {
		in, out := &in.Subnets2, &out.Subnets2
		*out = make(DockerClusterSubnets2, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Subnets3 != nil {
		in, out := &in.Subnets3, &out.Subnets3
		*out = make(DockerClusterSubnets3, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Subnets4 != nil {
		in, out := &in.Subnets4, &out.Subnets4
		*out = make(DockerClusterSubnets4, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterSpec.
func (in *DockerClusterSpec) DeepCopy() *DockerClusterSpec {
	if in == nil {
		return nil
	}
	out := new(DockerClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterStatus) DeepCopyInto(out *DockerClusterStatus) {
	*out = *in
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make(apiv1beta1.FailureDomains, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterStatus.
func (in *DockerClusterStatus) DeepCopy() *DockerClusterStatus {
	if in == nil {
		return nil
	}
	out := new(DockerClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DockerClusterSubnets1) DeepCopyInto(out *DockerClusterSubnets1) {
	{
		in := &in
		*out = make(DockerClusterSubnets1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterSubnets1.
func (in DockerClusterSubnets1) DeepCopy() DockerClusterSubnets1 {
	if in == nil {
		return nil
	}
	out := new(DockerClusterSubnets1)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterSubnets1Spec) DeepCopyInto(out *DockerClusterSubnets1Spec) {
	*out = *in
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterSubnets1Spec.
func (in *DockerClusterSubnets1Spec) DeepCopy() *DockerClusterSubnets1Spec {
	if in == nil {
		return nil
	}
	out := new(DockerClusterSubnets1Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DockerClusterSubnets2) DeepCopyInto(out *DockerClusterSubnets2) {
	{
		in := &in
		*out = make(DockerClusterSubnets2, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterSubnets2.
func (in DockerClusterSubnets2) DeepCopy() DockerClusterSubnets2 {
	if in == nil {
		return nil
	}
	out := new(DockerClusterSubnets2)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterSubnets2Spec) DeepCopyInto(out *DockerClusterSubnets2Spec) {
	*out = *in
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterSubnets2Spec.
func (in *DockerClusterSubnets2Spec) DeepCopy() *DockerClusterSubnets2Spec {
	if in == nil {
		return nil
	}
	out := new(DockerClusterSubnets2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DockerClusterSubnets3) DeepCopyInto(out *DockerClusterSubnets3) {
	{
		in := &in
		*out = make(DockerClusterSubnets3, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterSubnets3.
func (in DockerClusterSubnets3) DeepCopy() DockerClusterSubnets3 {
	if in == nil {
		return nil
	}
	out := new(DockerClusterSubnets3)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterSubnets3Spec) DeepCopyInto(out *DockerClusterSubnets3Spec) {
	*out = *in
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterSubnets3Spec.
func (in *DockerClusterSubnets3Spec) DeepCopy() *DockerClusterSubnets3Spec {
	if in == nil {
		return nil
	}
	out := new(DockerClusterSubnets3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DockerClusterSubnets4) DeepCopyInto(out *DockerClusterSubnets4) {
	{
		in := &in
		*out = make(DockerClusterSubnets4, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterSubnets4.
func (in DockerClusterSubnets4) DeepCopy() DockerClusterSubnets4 {
	if in == nil {
		return nil
	}
	out := new(DockerClusterSubnets4)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterSubnets4Spec) DeepCopyInto(out *DockerClusterSubnets4Spec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterSubnets4Spec.
func (in *DockerClusterSubnets4Spec) DeepCopy() *DockerClusterSubnets4Spec {
	if in == nil {
		return nil
	}
	out := new(DockerClusterSubnets4Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterTemplate) DeepCopyInto(out *DockerClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterTemplate.
func (in *DockerClusterTemplate) DeepCopy() *DockerClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(DockerClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterTemplateList) DeepCopyInto(out *DockerClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DockerClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterTemplateList.
func (in *DockerClusterTemplateList) DeepCopy() *DockerClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(DockerClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterTemplateNewSpec) DeepCopyInto(out *DockerClusterTemplateNewSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make(apiv1beta1.FailureDomains, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	out.LoadBalancer = in.LoadBalancer
	if in.Subnets1 != nil {
		in, out := &in.Subnets1, &out.Subnets1
		*out = make(DockerClusterTemplateSubnets1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Subnets2 != nil {
		in, out := &in.Subnets2, &out.Subnets2
		*out = make(DockerClusterTemplateSubnets2, len(*in))
		copy(*out, *in)
	}
	if in.Subnets3 != nil {
		in, out := &in.Subnets3, &out.Subnets3
		*out = make(DockerClusterTemplateSubnets3, len(*in))
		copy(*out, *in)
	}
	if in.Subnets4 != nil {
		in, out := &in.Subnets4, &out.Subnets4
		*out = make(DockerClusterTemplateSubnets4, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterTemplateNewSpec.
func (in *DockerClusterTemplateNewSpec) DeepCopy() *DockerClusterTemplateNewSpec {
	if in == nil {
		return nil
	}
	out := new(DockerClusterTemplateNewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterTemplateResource) DeepCopyInto(out *DockerClusterTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterTemplateResource.
func (in *DockerClusterTemplateResource) DeepCopy() *DockerClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(DockerClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterTemplateSpec) DeepCopyInto(out *DockerClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterTemplateSpec.
func (in *DockerClusterTemplateSpec) DeepCopy() *DockerClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(DockerClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DockerClusterTemplateSubnets1) DeepCopyInto(out *DockerClusterTemplateSubnets1) {
	{
		in := &in
		*out = make(DockerClusterTemplateSubnets1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterTemplateSubnets1.
func (in DockerClusterTemplateSubnets1) DeepCopy() DockerClusterTemplateSubnets1 {
	if in == nil {
		return nil
	}
	out := new(DockerClusterTemplateSubnets1)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterTemplateSubnets1Spec) DeepCopyInto(out *DockerClusterTemplateSubnets1Spec) {
	*out = *in
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterTemplateSubnets1Spec.
func (in *DockerClusterTemplateSubnets1Spec) DeepCopy() *DockerClusterTemplateSubnets1Spec {
	if in == nil {
		return nil
	}
	out := new(DockerClusterTemplateSubnets1Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DockerClusterTemplateSubnets2) DeepCopyInto(out *DockerClusterTemplateSubnets2) {
	{
		in := &in
		*out = make(DockerClusterTemplateSubnets2, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterTemplateSubnets2.
func (in DockerClusterTemplateSubnets2) DeepCopy() DockerClusterTemplateSubnets2 {
	if in == nil {
		return nil
	}
	out := new(DockerClusterTemplateSubnets2)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterTemplateSubnets2Spec) DeepCopyInto(out *DockerClusterTemplateSubnets2Spec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterTemplateSubnets2Spec.
func (in *DockerClusterTemplateSubnets2Spec) DeepCopy() *DockerClusterTemplateSubnets2Spec {
	if in == nil {
		return nil
	}
	out := new(DockerClusterTemplateSubnets2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DockerClusterTemplateSubnets3) DeepCopyInto(out *DockerClusterTemplateSubnets3) {
	{
		in := &in
		*out = make(DockerClusterTemplateSubnets3, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterTemplateSubnets3.
func (in DockerClusterTemplateSubnets3) DeepCopy() DockerClusterTemplateSubnets3 {
	if in == nil {
		return nil
	}
	out := new(DockerClusterTemplateSubnets3)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterTemplateSubnets3Spec) DeepCopyInto(out *DockerClusterTemplateSubnets3Spec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterTemplateSubnets3Spec.
func (in *DockerClusterTemplateSubnets3Spec) DeepCopy() *DockerClusterTemplateSubnets3Spec {
	if in == nil {
		return nil
	}
	out := new(DockerClusterTemplateSubnets3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DockerClusterTemplateSubnets4) DeepCopyInto(out *DockerClusterTemplateSubnets4) {
	{
		in := &in
		*out = make(DockerClusterTemplateSubnets4, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterTemplateSubnets4.
func (in DockerClusterTemplateSubnets4) DeepCopy() DockerClusterTemplateSubnets4 {
	if in == nil {
		return nil
	}
	out := new(DockerClusterTemplateSubnets4)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterTemplateSubnets4Spec) DeepCopyInto(out *DockerClusterTemplateSubnets4Spec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterTemplateSubnets4Spec.
func (in *DockerClusterTemplateSubnets4Spec) DeepCopy() *DockerClusterTemplateSubnets4Spec {
	if in == nil {
		return nil
	}
	out := new(DockerClusterTemplateSubnets4Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerLoadBalancer) DeepCopyInto(out *DockerLoadBalancer) {
	*out = *in
	out.ImageMeta = in.ImageMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerLoadBalancer.
func (in *DockerLoadBalancer) DeepCopy() *DockerLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(DockerLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerMachine) DeepCopyInto(out *DockerMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerMachine.
func (in *DockerMachine) DeepCopy() *DockerMachine {
	if in == nil {
		return nil
	}
	out := new(DockerMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerMachineList) DeepCopyInto(out *DockerMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DockerMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerMachineList.
func (in *DockerMachineList) DeepCopy() *DockerMachineList {
	if in == nil {
		return nil
	}
	out := new(DockerMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerMachineSpec) DeepCopyInto(out *DockerMachineSpec) {
	*out = *in
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.PreLoadImages != nil {
		in, out := &in.PreLoadImages, &out.PreLoadImages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraMounts != nil {
		in, out := &in.ExtraMounts, &out.ExtraMounts
		*out = make([]Mount, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerMachineSpec.
func (in *DockerMachineSpec) DeepCopy() *DockerMachineSpec {
	if in == nil {
		return nil
	}
	out := new(DockerMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerMachineStatus) DeepCopyInto(out *DockerMachineStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]apiv1beta1.MachineAddress, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerMachineStatus.
func (in *DockerMachineStatus) DeepCopy() *DockerMachineStatus {
	if in == nil {
		return nil
	}
	out := new(DockerMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerMachineTemplate) DeepCopyInto(out *DockerMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerMachineTemplate.
func (in *DockerMachineTemplate) DeepCopy() *DockerMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(DockerMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerMachineTemplateList) DeepCopyInto(out *DockerMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DockerMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerMachineTemplateList.
func (in *DockerMachineTemplateList) DeepCopy() *DockerMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(DockerMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerMachineTemplateResource) DeepCopyInto(out *DockerMachineTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerMachineTemplateResource.
func (in *DockerMachineTemplateResource) DeepCopy() *DockerMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(DockerMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerMachineTemplateSpec) DeepCopyInto(out *DockerMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerMachineTemplateSpec.
func (in *DockerMachineTemplateSpec) DeepCopy() *DockerMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(DockerMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageMeta) DeepCopyInto(out *ImageMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageMeta.
func (in *ImageMeta) DeepCopy() *ImageMeta {
	if in == nil {
		return nil
	}
	out := new(ImageMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mount) DeepCopyInto(out *Mount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mount.
func (in *Mount) DeepCopy() *Mount {
	if in == nil {
		return nil
	}
	out := new(Mount)
	in.DeepCopyInto(out)
	return out
}
