//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	corev1beta1 "sigs.k8s.io/cluster-api/api/core/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIEndpoint) DeepCopyInto(out *APIEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIEndpoint.
func (in *APIEndpoint) DeepCopy() *APIEndpoint {
	if in == nil {
		return nil
	}
	out := new(APIEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonProvisioningSettings) DeepCopyInto(out *CommonProvisioningSettings) {
	*out = *in
	out.StartupDuration = in.StartupDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonProvisioningSettings.
func (in *CommonProvisioningSettings) DeepCopy() *CommonProvisioningSettings {
	if in == nil {
		return nil
	}
	out := new(CommonProvisioningSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevCluster) DeepCopyInto(out *DevCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevCluster.
func (in *DevCluster) DeepCopy() *DevCluster {
	if in == nil {
		return nil
	}
	out := new(DevCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevClusterBackendSpec) DeepCopyInto(out *DevClusterBackendSpec) {
	*out = *in
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = new(DockerClusterBackendSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.InMemory != nil {
		in, out := &in.InMemory, &out.InMemory
		*out = new(InMemoryClusterBackendSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevClusterBackendSpec.
func (in *DevClusterBackendSpec) DeepCopy() *DevClusterBackendSpec {
	if in == nil {
		return nil
	}
	out := new(DevClusterBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevClusterList) DeepCopyInto(out *DevClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevClusterList.
func (in *DevClusterList) DeepCopy() *DevClusterList {
	if in == nil {
		return nil
	}
	out := new(DevClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevClusterSpec) DeepCopyInto(out *DevClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	in.Backend.DeepCopyInto(&out.Backend)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevClusterSpec.
func (in *DevClusterSpec) DeepCopy() *DevClusterSpec {
	if in == nil {
		return nil
	}
	out := new(DevClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevClusterStatus) DeepCopyInto(out *DevClusterStatus) {
	*out = *in
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make(corev1beta1.FailureDomains, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.V1Beta2 != nil {
		in, out := &in.V1Beta2, &out.V1Beta2
		*out = new(DevClusterV1Beta2Status)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevClusterStatus.
func (in *DevClusterStatus) DeepCopy() *DevClusterStatus {
	if in == nil {
		return nil
	}
	out := new(DevClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevClusterTemplate) DeepCopyInto(out *DevClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevClusterTemplate.
func (in *DevClusterTemplate) DeepCopy() *DevClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(DevClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevClusterTemplateList) DeepCopyInto(out *DevClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevClusterTemplateList.
func (in *DevClusterTemplateList) DeepCopy() *DevClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(DevClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevClusterTemplateResource) DeepCopyInto(out *DevClusterTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevClusterTemplateResource.
func (in *DevClusterTemplateResource) DeepCopy() *DevClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(DevClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevClusterTemplateSpec) DeepCopyInto(out *DevClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevClusterTemplateSpec.
func (in *DevClusterTemplateSpec) DeepCopy() *DevClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(DevClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevClusterV1Beta2Status) DeepCopyInto(out *DevClusterV1Beta2Status) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevClusterV1Beta2Status.
func (in *DevClusterV1Beta2Status) DeepCopy() *DevClusterV1Beta2Status {
	if in == nil {
		return nil
	}
	out := new(DevClusterV1Beta2Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevMachine) DeepCopyInto(out *DevMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevMachine.
func (in *DevMachine) DeepCopy() *DevMachine {
	if in == nil {
		return nil
	}
	out := new(DevMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevMachineBackendSpec) DeepCopyInto(out *DevMachineBackendSpec) {
	*out = *in
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = new(DockerMachineBackendSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.InMemory != nil {
		in, out := &in.InMemory, &out.InMemory
		*out = new(InMemoryMachineBackendSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevMachineBackendSpec.
func (in *DevMachineBackendSpec) DeepCopy() *DevMachineBackendSpec {
	if in == nil {
		return nil
	}
	out := new(DevMachineBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevMachineList) DeepCopyInto(out *DevMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevMachineList.
func (in *DevMachineList) DeepCopy() *DevMachineList {
	if in == nil {
		return nil
	}
	out := new(DevMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevMachineSpec) DeepCopyInto(out *DevMachineSpec) {
	*out = *in
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	in.Backend.DeepCopyInto(&out.Backend)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevMachineSpec.
func (in *DevMachineSpec) DeepCopy() *DevMachineSpec {
	if in == nil {
		return nil
	}
	out := new(DevMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevMachineStatus) DeepCopyInto(out *DevMachineStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]corev1beta1.MachineAddress, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.V1Beta2 != nil {
		in, out := &in.V1Beta2, &out.V1Beta2
		*out = new(DevMachineV1Beta2Status)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevMachineStatus.
func (in *DevMachineStatus) DeepCopy() *DevMachineStatus {
	if in == nil {
		return nil
	}
	out := new(DevMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevMachineTemplate) DeepCopyInto(out *DevMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevMachineTemplate.
func (in *DevMachineTemplate) DeepCopy() *DevMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(DevMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevMachineTemplateList) DeepCopyInto(out *DevMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevMachineTemplateList.
func (in *DevMachineTemplateList) DeepCopy() *DevMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(DevMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevMachineTemplateResource) DeepCopyInto(out *DevMachineTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevMachineTemplateResource.
func (in *DevMachineTemplateResource) DeepCopy() *DevMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(DevMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevMachineTemplateSpec) DeepCopyInto(out *DevMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevMachineTemplateSpec.
func (in *DevMachineTemplateSpec) DeepCopy() *DevMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(DevMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevMachineV1Beta2Status) DeepCopyInto(out *DevMachineV1Beta2Status) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevMachineV1Beta2Status.
func (in *DevMachineV1Beta2Status) DeepCopy() *DevMachineV1Beta2Status {
	if in == nil {
		return nil
	}
	out := new(DevMachineV1Beta2Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterBackendSpec) DeepCopyInto(out *DockerClusterBackendSpec) {
	*out = *in
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make(corev1beta1.FailureDomains, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.LoadBalancer.DeepCopyInto(&out.LoadBalancer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterBackendSpec.
func (in *DockerClusterBackendSpec) DeepCopy() *DockerClusterBackendSpec {
	if in == nil {
		return nil
	}
	out := new(DockerClusterBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerLoadBalancer) DeepCopyInto(out *DockerLoadBalancer) {
	*out = *in
	out.ImageMeta = in.ImageMeta
	if in.CustomHAProxyConfigTemplateRef != nil {
		in, out := &in.CustomHAProxyConfigTemplateRef, &out.CustomHAProxyConfigTemplateRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerLoadBalancer.
func (in *DockerLoadBalancer) DeepCopy() *DockerLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(DockerLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerMachineBackendSpec) DeepCopyInto(out *DockerMachineBackendSpec) {
	*out = *in
	if in.PreLoadImages != nil {
		in, out := &in.PreLoadImages, &out.PreLoadImages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraMounts != nil {
		in, out := &in.ExtraMounts, &out.ExtraMounts
		*out = make([]Mount, len(*in))
		copy(*out, *in)
	}
	if in.BootstrapTimeout != nil {
		in, out := &in.BootstrapTimeout, &out.BootstrapTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerMachineBackendSpec.
func (in *DockerMachineBackendSpec) DeepCopy() *DockerMachineBackendSpec {
	if in == nil {
		return nil
	}
	out := new(DockerMachineBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageMeta) DeepCopyInto(out *ImageMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageMeta.
func (in *ImageMeta) DeepCopy() *ImageMeta {
	if in == nil {
		return nil
	}
	out := new(ImageMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InMemoryAPIServerSpec) DeepCopyInto(out *InMemoryAPIServerSpec) {
	*out = *in
	out.Provisioning = in.Provisioning
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InMemoryAPIServerSpec.
func (in *InMemoryAPIServerSpec) DeepCopy() *InMemoryAPIServerSpec {
	if in == nil {
		return nil
	}
	out := new(InMemoryAPIServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InMemoryClusterBackendSpec) DeepCopyInto(out *InMemoryClusterBackendSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InMemoryClusterBackendSpec.
func (in *InMemoryClusterBackendSpec) DeepCopy() *InMemoryClusterBackendSpec {
	if in == nil {
		return nil
	}
	out := new(InMemoryClusterBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InMemoryEtcdSpec) DeepCopyInto(out *InMemoryEtcdSpec) {
	*out = *in
	out.Provisioning = in.Provisioning
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InMemoryEtcdSpec.
func (in *InMemoryEtcdSpec) DeepCopy() *InMemoryEtcdSpec {
	if in == nil {
		return nil
	}
	out := new(InMemoryEtcdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InMemoryMachineBackendSpec) DeepCopyInto(out *InMemoryMachineBackendSpec) {
	*out = *in
	if in.VM != nil {
		in, out := &in.VM, &out.VM
		*out = new(InMemoryVMSpec)
		**out = **in
	}
	if in.Node != nil {
		in, out := &in.Node, &out.Node
		*out = new(InMemoryNodeSpec)
		**out = **in
	}
	if in.APIServer != nil {
		in, out := &in.APIServer, &out.APIServer
		*out = new(InMemoryAPIServerSpec)
		**out = **in
	}
	if in.Etcd != nil {
		in, out := &in.Etcd, &out.Etcd
		*out = new(InMemoryEtcdSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InMemoryMachineBackendSpec.
func (in *InMemoryMachineBackendSpec) DeepCopy() *InMemoryMachineBackendSpec {
	if in == nil {
		return nil
	}
	out := new(InMemoryMachineBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InMemoryNodeSpec) DeepCopyInto(out *InMemoryNodeSpec) {
	*out = *in
	out.Provisioning = in.Provisioning
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InMemoryNodeSpec.
func (in *InMemoryNodeSpec) DeepCopy() *InMemoryNodeSpec {
	if in == nil {
		return nil
	}
	out := new(InMemoryNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InMemoryVMSpec) DeepCopyInto(out *InMemoryVMSpec) {
	*out = *in
	out.Provisioning = in.Provisioning
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InMemoryVMSpec.
func (in *InMemoryVMSpec) DeepCopy() *InMemoryVMSpec {
	if in == nil {
		return nil
	}
	out := new(InMemoryVMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mount) DeepCopyInto(out *Mount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mount.
func (in *Mount) DeepCopy() *Mount {
	if in == nil {
		return nil
	}
	out := new(Mount)
	in.DeepCopyInto(out)
	return out
}
